apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.configServer.name }}-conf
data:
  server.config: |
{{ include "ri-firewall.serverArgs" . | indent 4 }}
    configServer:
      firewallSystemConfigName: {{ include "ri-firewall.firewallSystemConfigMapName" . }}
      firewallUserConfigName: {{ include "ri-firewall.firewallUserConfigMapName" . }}
      firewallDeploymentName: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.firewallServer.name }}
