apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.operator.name }}
  annotations:
    {{- include "ri-firewall.annotations" . | nindent 4 }}
    {{- with .Values.riFirewall.operator.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    checksum/config: {{ include (print $.Template.BasePath "/operator/configmap.yaml") . | sha256sum }}
  labels:
    app: {{ .Values.riFirewall.operator.name }}
    {{- include "ri-firewall.labels" . | nindent 4 }}
    {{- with .Values.riFirewall.operator.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.riFirewall.operator.name }}
  replicas: {{ .Values.riFirewall.operator.deployment.replicaCount }}
  template:
    metadata:
      annotations:
        {{- include "ri-firewall.annotations" . | nindent 8 }}
        {{- with .Values.riFirewall.operator.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Values.riFirewall.operator.name }}
        {{- include "ri-firewall.labels" . | nindent 8 }}
        {{- with .Values.riFirewall.operator.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.riFirewall.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ri-firewall.operator.serviceAccountName" . }}
      containers:
      - name: controller-manager
        image: "{{ .Values.riFirewall.images.backendImage.registry}}/{{ .Values.riFirewall.images.backendImage.name }}"
        imagePullPolicy: {{ .Values.riFirewall.images.backendImage.pullPolicy }}
        env:
          - name: RI_SERVICE_NAME
            value: {{ .Values.riFirewall.operator.name }}
          {{- if .Values.riFirewall.registerFirewallAgent.enabled }}
          - name: AGENT_ID
            value: {{ .Values.riFirewall.registerFirewallAgent.agentID }}
          {{- end }}
        resources:
            {{- toYaml .Values.riFirewall.operator.deployment.resources | nindent 12 }}
        command:
        - "/ri/firewall"
        args:
        - "start-operator"
        - "--leader-elect"
        - "--app-name={{ include "ri-firewall.fullname" . }}"
        - "--configmap-template-path=/config/firewall-instance-configmap.config"
        - "--deployment-template-path=/config/firewall-instance-deployment.config"
        - "--ingress-template-path=/config/firewall-instance-ingress.config"
        - "--snowflake-ingress-template-path=/config/snowflake-ingress.config"
        - "--service-template-path=/config/firewall-instance-service.config"
        - "--hpa-template-path=/config/firewall-instance-hpa.config"
        - "--pdb-template-path=/config/inference-service-pdb.config"
        - "--yara-server-template-path=/config/yara-server.config"
        - "--inference-service-template-path=/config/inference-service.config"
        - "--triton-inference-service-template-path=/config/triton-inference-service.config"
        - "--model-server-configmap-template-path=/config/model-settings-configmap.config"
        - "--template-checksum={{ include (print $.Template.BasePath "/operator/configmap.yaml") . | sha256sum }}"
        {{- if .Values.riFirewall.operator.firewallInstanceIngress.disabled }}
        - "--disable-ingress-for-firewall-instance"
        {{- end }}
        {{- if not .Values.riFirewall.operator.guardrailSnowflakeIngress.enabled }}
        - "--disable-snowflake-ingress-for-firewall-instance"
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.operator.name }}-config
          mountPath: "/config"
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.operator.name }}-config
          configMap:
            name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.operator.name }}-conf
            items:
              - key: "firewall-instance-configmap.config"
                path: "firewall-instance-configmap.config"
              - key: "firewall-instance-deployment.config"
                path: "firewall-instance-deployment.config"
              - key: "firewall-instance-service.config"
                path: "firewall-instance-service.config"
              - key: "firewall-instance-ingress.config"
                path: "firewall-instance-ingress.config"
              - key: "snowflake-ingress.config"
                path: "snowflake-ingress.config"
              - key: "firewall-instance-hpa.config"
                path: "firewall-instance-hpa.config"
              - key: "inference-service.config"
                path: "inference-service.config"
              - key: "triton-inference-service.config"
                path: "triton-inference-service.config"
              - key: "inference-service-pdb.config"
                path: "inference-service-pdb.config"
              - key: "model-settings-configmap.config"
                path: "model-settings-configmap.config"
              - key: "yara-server.config"
                path: "yara-server.config"
      {{- with .Values.riFirewall.operator.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.riFirewall.operator.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.riFirewall.operator.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.riFirewall.operator.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
