apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ri-firewall.fullname" . }}-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.operator.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "ri-firewall.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
