{{- if .Values.riFirewall.productionOptimizations.overprovisionGPUNode.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overprovision-gpu
  labels:
    {{- include "ri-firewall.labels" . | nindent 4 }}
  annotations:
    {{- include "ri-firewall.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: overprovision-gpu
  replicas: {{ .Values.riFirewall.productionOptimizations.overprovisionGPUNode.poolSize }}
  template:
    metadata:
      labels:
        app: overprovision-gpu
        {{- include "ri-firewall.labels" . | nindent 8 }}
      annotations:
        {{- include "ri-firewall.annotations" . | nindent 8 }}
    spec:
      priorityClassName: overprovisioning
      {{- with .Values.riFirewall.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # Container to pull and cache model server image.
        - name: model-server-resources
          image: "{{ .Values.riFirewall.images.modelServerImage.registry}}/{{ .Values.riFirewall.images.modelServerImage.name }}"
          imagePullPolicy: {{ .Values.riFirewall.images.backendImage.pullPolicy }}
          resources:
            requests:
              {{- toYaml .Values.riFirewall.productionOptimizations.overprovisionGPUNode.resources | nindent 14 }}
            limits:
              {{- toYaml .Values.riFirewall.productionOptimizations.overprovisionGPUNode.resources | nindent 14 }}
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: gpu-dedicated
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: "overprovision-gpu"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: "overprovision-compute"
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: "overprovision-compute"
              topologyKey: kubernetes.io/hostname
            weight: 99
{{- end }}
