{{- if .Values.aiValidation.generativeValidationService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-validation.fullname" . }}-{{ .Values.aiValidation.generativeValidationService.name }}-conf
data:
  server.config: |
{{ include "ai-validation.serverArgs" . | indent 4 }}
{{- end }}
