rimeSystem:
  clusterAutoscaler: false
  externalDns: false
  awsLoadBalancerController: false
  metricsServer: false

aws-load-balancer-controller:
  image:
    repository: "docker.io/robustintelligencehq/aws-alb-ingress-controller"
    tag: "v2.4.2"
  clusterName: ""
  serviceAccount:
    create: true
  region: ""

cluster-autoscaler:
  image:
    repository: "docker.io/robustintelligencehq/cluster-autoscaler"
    tag: "v1.21.0"
  podAnnotations: {
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  }
  cloudProvider: aws

external-dns:
  image:
    repository: "docker.io/robustintelligencehq/external-dns"
    tag: "v0.12.0"
  provider: "aws"
  policy: sync
  registry: txt
  txtOwnerId: "rime"
  rbac:
    create: true
  serviceAccount:
    name: external-dns
    annotations:
  logFormat: json

metrics-server:
  image:
    repository: "docker.io/robustintelligencehq/metrics-server"
    tag: "v0.6.1"
  apiService:
    create: true

cert-manager:
  enabled: true
  installCRDs: true
  global:
    imagePullSecrets:
      - name: rimecreds
  image:
    registry: docker.io
    repository: robustintelligencehq/cert-manager-controller
  webhook:
    image:
      registry: docker.io
      repository: robustintelligencehq/cert-manager-webhook
  cainjector:
    image:
      registry: docker.io
      repository: robustintelligencehq/cert-manager-cainjector
  startupapicheck:
    image:
      registry: docker.io
      repository: robustintelligencehq/cert-manager-ctl
