apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rime.fullname" . }}-agent-manager-server
  labels:
    app: agent-manager-server
    {{- include "rime.labels" . | nindent 4 }}
    tags.datadoghq.com/service: agent-manager-server
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: agent-manager-server
      {{- include "rime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: agent-manager-server
        {{- include "rime.selectorLabels" . | nindent 8 }}
        tags.datadoghq.com/service: agent-manager-server
      annotations:
        {{- include "prometheusScrapingAnnotations" . | nindent 8 }}
        {{- if .Values.rime.datadogTagPodAnnotation }}
        ad.datadoghq.com/tags: '{{ .Values.rime.datadogTagPodAnnotation }}'
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- include "rime.commonEnv" . | nindent 12 }}
            - name: DOCKER_CREDS_JSON
              valueFrom:
                secretKeyRef:
                  {{- if gt (len .Values.imagePullSecrets) 0 }}
                  name: {{ (index .Values.imagePullSecrets 0).name }}
                  {{- else }}
                  name: rimecreds
                  {{- end }}
                  key: .dockerconfigjson
          image: "{{ .Values.backendImage.name }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          ports:
            - name: agent
              containerPort: {{ .Values.ports.agentManagerServer }}
              protocol: TCP
            - name: agent-rest
              containerPort: {{ .Values.ports.agentManagerREST }}
              protocol: TCP
            - name: agent-debug
              containerPort: 6060
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.ports.agentManagerServer }}"]
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.ports.agentManagerServer }}"]
            periodSeconds: 5
          startupProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.ports.agentManagerServer }}"]
            failureThreshold: 60
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - "/rime/rime"
          args:
            - "start-agent-manager-server"
            - "--server-config-path=/config/server.config"
            - "--database-url={{ include "rime.fullname" . }}-mongodb-headless/?tls=false"
            - "--database-url-prefix=mongodb+srv://"
            - "--redis-addr={{ include "rime.fullname" . }}-redis-headless:6379"
            - "--agent-manager-port={{ .Values.ports.agentManagerServer }}"
            - "--agent-manager-rest-port={{ .Values.ports.agentManagerREST }}"
            {{- if .Values.prometheusMetricsExposition.enabled }}
            - "--metrics-exposition-enabled=true"
            - "--metrics-exposition-port={{ .Values.prometheusMetricsExposition.port }}"
            {{- end }}
            - "--docker-creds-json=$(DOCKER_CREDS_JSON)"
            - "--platform-address-domain={{ .Values.rime.domain }}"
            - "--auth-server-addr={{ include "rime.fullname" . }}-auth-server:{{ .Values.ports.userServer }}"
            - "--job-manager-addr={{ include "rime.fullname" . }}-upload-server:{{ .Values.ports.upload}}"
            - "--job-reader-addr={{ include "rime.fullname" . }}-grpc-web-server:{{ .Values.ports.grpcWebServer}}"
            - "--request-queue-proxy-addr={{ include "rime.fullname" . }}-request-queue-proxy:{{ .Values.ports.requestQueueProxy}}"
            {{- if .Values.rime.verbose }}
            - "--verbose"
            {{- end }}
          volumeMounts:
          - name: {{ include "rime.fullname" . }}-agent-manager-config
            mountPath: "/config"
            readOnly: true
      volumes:
      # Volumes are defined at the Pod level, then mounted into containers within that Pod
      - name: {{ include "rime.fullname" . }}-agent-manager-config
        configMap:
          name: {{ include "rime.fullname" . }}-agent-manager-conf
          items:
          - key: "server.config"
            path: "server.config"
