apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rime.fullname" . }}-auth-ingress
  labels:
    {{- include "rime.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.rime.ipAllowlist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: '{{ join "," .Values.rime.ipAllowlist }}'
    {{- end }}
spec:
  {{ if .Values.rime.certificateSecretName}}
  tls:
    - hosts:
        - "*.{{ .Values.rime.domain }}"
    - secretName: {{ .Values.rime.certificateSecretName }}
  {{ end }}
  rules:
    - http:
        paths:
          - path: /v1/auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-auth-server
                port:
                  name: auth-server
          - path: /v1/rime-info
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-frontend
                port:
                  name: frontend
