{{- if .Values.databaseSetup.indexCreationHook.dropDuplicates }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rime.fullname" . }}-drop-duplicates
  labels:
    tags.datadoghq.com/service: drop-duplicates
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # NOTE: post-upgrade relies on the database-setup script being idempotent.
    "helm.sh/hook": post-install,post-upgrade
    # Hooks are sorted in ascending order.
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/service: drop-duplicates
      annotations:
        {{- if .Values.rime.datadogTagPodAnnotation }}
        ad.datadoghq.com/tags: '{{ .Values.rime.datadogTagPodAnnotation }}'
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: database-setup
          image: "{{ .Values.backendImage.name }}"
          imagePullPolicy: "{{ .Values.backendImage.pullPolicy }}"
          command:
            - "/rime/dbworker"
          args:
            - "drop-duplicates"
            - "-database-name=rime-store"
            - "--database-url={{ include "rime.fullname" . }}-mongodb-headless/?tls=false"
            - "--database-url-prefix=mongodb+srv://"
            - "-replica-set-name={{ .Values.mongodb.replicaSetName }}"
            # 4 minute timeout because the maximum execution time for a helm chart hook is 5 min.
            - "-timeout=4m"
            {{- if .Values.rime.verbose }}
            - "-verbose"
            {{- end }}
            {{- if .Values.databaseSetup.debug }}
            - "-debug"
            {{- end}}
      restartPolicy: OnFailure
  backoffLimit: {{ .Values.databaseSetup.indexCreationHook.backoffLimit }}
{{- end }}
