apiVersion: v1
kind: Service
metadata:
  name: {{ include "rime.fullname" . }}-feature-flag-server
  labels:
    {{- include "rime.labels" . | nindent 4 }}
  annotations:
    konghq.com/protocol: "grpc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.featureFlagServer }}
      targetPort: featureflag
      protocol: TCP
      name: featureflag
    - port: {{ .Values.ports.featureFlagServerREST }}
      targetPort: fflag-rest
      protocol: TCP
      name: fflag-rest
  selector:
    app: feature-flag-server
    {{- include "rime.selectorLabels" . | nindent 4 }}
