apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rime.fullname" . }}-ingress
  labels:
    {{- include "rime.labels" . | nindent 4 }}
    {{- with .Values.rime.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.tls.restEnabled }}
    nginx.ingress.kubernetes.io/auth-url: https://{{ include "rime.fullname" . }}-{{ .Values.rime.authServer.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.rime.authServer.port}}/v1/auth/validate
    {{- else }}
    nginx.ingress.kubernetes.io/auth-url: http://{{ include "rime.fullname" . }}-{{ .Values.rime.authServer.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.rime.authServer.port}}/v1/auth/validate
    {{- end }}
    nginx.ingress.kubernetes.io/auth-method: POST
    nginx.ingress.kubernetes.io/auth-response-headers: X-Rime-User, X-Rime-Api-Key, X-Rime-Api-Key-Name, X-Rime-Workspace, X-Rime-Client-Internal-Token, X-Rime-Agent
    {{- if .Values.tls.restEnabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "{{.Release.Namespace}}/{{ include "rime.fullname" . }}-ingress-tls"
    nginx.ingress.kubernetes.io/proxy-ssl-name: "{{ include "rime.fullname" . }}-ingress-server"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "sameorigin";
      add_header X-Content-Type-Options "nosniff";
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    {{- with .Values.rime.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.rime.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /internal/images
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.imageRegistryServer.name }}
                port:
                  number: {{ .Values.rime.imageRegistryServer.restPort }}
          - path: /internal/secrets
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/registry
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.uploadServer.name }}
                port:
                  number:  {{ .Values.rime.uploadServer.restPort }}
          - path: /internal/file-scan-results
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.uploadServer.name }}
                port:
                  number:  {{ .Values.rime.uploadServer.restPort }}
          - path: /internal/result-synth
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.uploadServer.name }}
                port:
                  number:  {{ .Values.rime.uploadServer.restPort }}
          - path: /v1/users
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.authServer.name }}
                port:
                  number: {{ .Values.rime.authServer.grpcRestPort }}
          - path: /v1/batch-results
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1-beta/datasets
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.datasetManagerServer.name }}
                port:
                  number: {{ .Values.rime.datasetManagerServer.restPort }}
          - path: /v1-beta/models
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.datasetManagerServer.name }}
                port:
                  number: {{ .Values.rime.datasetManagerServer.restPort }}
          - path: /v1-beta/uploaded-file-urls
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.datasetManagerServer.name }}
                port:
                  number: {{ .Values.rime.datasetManagerServer.restPort }}
          - path: /v1/feature-results
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/summary-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/feature-flags
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.featureFlagServer.name }}
                port:
                  number: {{ .Values.rime.featureFlagServer.restPort }}
          - path: /internal/feature-flags
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-feature-flag-server
                port:
                  number: {{ .Values.rime.featureFlagServer.restPort }}
          - path: /v1/agents
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.agentManagerServer.name }}
                port:
                  number: {{ .Values.rime.agentManagerServer.restPort }}
          - path: /internal/agents
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.agentManagerServer.name }}
                port:
                  number: {{ .Values.rime.agentManagerServer.restPort }}
          - path: /internal/statedb
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.uploadServer.name }}
                port:
                  number: {{ .Values.rime.uploadServer.restPort }}
          - path: /v1/notif-settings
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1-beta/data-collector
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.dataCollectorServer.name }}
                port:
                  number: {{ .Values.rime.dataCollectorServer.restPort }}
          - path: /v1-beta/firewall
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.firewallServer.name }}
                port:
                  number: {{ .Values.rime.firewallServer.restPort }}
          - path: /v1/firewall
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.firewallServer.name }}
                port:
                  number: {{ .Values.rime.firewallServer.restPort }}
          - path: /v1-beta/monitors
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.firewallServer.name }}
                port:
                  number: {{ .Values.rime.firewallServer.restPort }}
          - path: /v1-beta/custom-monitors
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.firewallServer.name }}
                port:
                  number: {{ .Values.rime.firewallServer.restPort }}
          - path: /v1-beta/detection-events
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.firewallServer.name }}
                port:
                  number: {{ .Values.rime.firewallServer.restPort }}
          - path: /v1-beta/file-scans
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}
                port:
                  number: {{ .Values.rime.modelTestingServer.restPort }}
          - path: /internal/generative-stress-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}
                port:
                  number: {{ .Values.rime.modelTestingServer.restPort }}
          - path: /internal/logs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}
                port:
                  number: {{ .Values.rime.modelTestingServer.restPort }}
          - path: /v1-beta/modelcards
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/images
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.imageRegistryServer.name }}
                port:
                  number: {{ .Values.rime.imageRegistryServer.restPort }}
          - path: /v1/jobs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/organizations
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/projects
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/stress-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}
                port:
                  number: {{ .Values.rime.modelTestingServer.restPort }}
          - path: /v1/continuous-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}
                port:
                  number: {{ .Values.rime.modelTestingServer.restPort }}
          - path: /v1/test-cases
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/test-runs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1/workspace
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1-beta/integrations
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /internal/config-validator
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          # TODO(RAT-1738): remove this ingress rule when we remove the toy example.
          - path: /internal/fooexample
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.grpcRestPort }}
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.webServer.name }}
                port:
                  number: {{ .Values.rime.webServer.port }}
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.frontendServer.name }}
                port:
                  number: {{ .Values.rime.frontendServer.port }}
          - path: /bff
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-{{ .Values.rime.frontendServer.name }}
                port:
                  number: {{ .Values.rime.frontendServer.port }}
