apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rime.fullname" . }}-ingress
  labels:
    {{- include "rime.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: "rime.{{ .Values.rime.domain }}"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.rime.ipAllowlist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: '{{ join "," .Values.rime.ipAllowlist }}'
    {{- end }}
    nginx.ingress.kubernetes.io/auth-url: http://{{ include "rime.fullname" . }}-auth-server.{{.Release.Namespace}}.svc.cluster.local:{{.Values.ports.authServer}}/v1/auth/validate
    nginx.ingress.kubernetes.io/auth-method: POST
    nginx.ingress.kubernetes.io/auth-response-headers: X-Rime-User, X-Rime-Api-Key, X-Rime-Api-Key-Name, X-Rime-Workspace
    nginx.ingress.kubernetes.io/proxy-read-timeout:	"120"
spec:
  {{ if .Values.rime.certificateSecretName}}
  tls:
    - hosts:
        - "*.{{ .Values.rime.domain }}"
    - secretName: {{ .Values.rime.certificateSecretName }}
  {{ end }}
  rules:
    - http:
        paths:
          - path: /v1/users
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-auth-server
                port:
                  name: user-rest
          - path: /v1/batch-results
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/datasets
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-dataset-manager
                port:
                  number: {{ .Values.ports.datasetManagerREST }}
          - path: /v1/models
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-dataset-manager
                port:
                  number: {{ .Values.ports.datasetManagerREST }}
          - path: /v1/uploaded-file-urls
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-dataset-manager
                port:
                  number: {{ .Values.ports.datasetManagerREST }}
          - path: /v1/feature-results
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/summary-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/feature-flags
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-feature-flag-server
                port:
                  number: {{ .Values.ports.featureFlagServerREST }}
          - path: /v1/agents
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-agent-manager-server
                port:
                  number: {{ .Values.ports.agentManagerREST }}
          - path: /v1/notif-settings
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/datacollector/datapoints
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-data-collector-server
                port:
                  number: {{ .Values.ports.dataCollectorREST }}
          - path: /v1/firewall
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-firewall-server
                port:
                  number: {{ .Values.ports.firewallREST }}
          - path: /v1/firewall/data
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/firewall/incremental
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/firewall/reference
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/file-scans
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/modelcards
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-card
                port:
                  number: {{ .Values.ports.modelCardREST }}
          - path: /v1/images
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-image-registry
                port:
                  number: {{ .Values.ports.imageRegistryREST }}
          - path: /v1/logs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/jobs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/organizations
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/projects
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/stress-tests
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-model-testing
                port:
                  number: {{ .Values.ports.modelTestingREST }}
          - path: /v1/test-cases
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/test-runs
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/workspace
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1/data-sources
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  number: {{ .Values.ports.grpcWebREST }}
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "rime.fullname" . }}-grpc-web-server
                port:
                  name: nativerestweb

