{{- if and .Values.modelTesting.rbac.create .Values.modelTesting.rbac.serviceAccount.create -}}
# Service account for the Model Testing Service.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "modelTesting.serviceAccountName" . }}
{{- with .Values.modelTesting.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
{{- end }}
