apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rime.fullname" . }}-secret-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rime.fullname" . }}-secret-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "rime.fullname" . }}-grpc-web-server-service-account
