{{- if (not .Values.rime.secrets.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime.commonSecretName" . }}
type: Opaque
data:
  adminUsername: {{ .Values.rime.secrets.admin.username | b64enc | quote }}
  adminPassword: {{ .Values.rime.secrets.admin.password | b64enc | quote }}
  oidcClientSecret: {{ .Values.rime.secrets.oidc.clientSecret | b64enc | quote }}
  oidcClientID: {{ .Values.rime.secrets.oidc.clientID | b64enc | quote }}
  oidcIssuerURL: {{ .Values.rime.secrets.oidc.issuerURL | b64enc | quote }}
  rimeLicense: {{ .Values.rime.secrets.rimeLicense | b64enc | quote }}
{{- end }}
