apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rime.secrets" . }}
type: Opaque
{{ $adminSecretData := (lookup "v1" "Secret" .Release.Namespace .Values.rime.adminSecretName) }}
{{- if $adminSecretData }}
data:
  admin-username:  {{  index $adminSecretData "data" "admin-username" }}
  admin-password:  {{  index $adminSecretData "data" "admin-password" }}
{{- else -}}
data:
  admin-username: {{ .Values.rime.adminUsername | b64enc | quote }}
  admin-password: {{ .Values.rime.adminPassword | b64enc | quote }}
{{ end }}
  # retrieve secret if it already exists
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "rime.secrets" .)) | default dict }}
  {{- $secretData := (get $secret "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 32 | b64enc) }}
  {{- $crossServiceKey := (get $secretData "cross-service-key") | default (randAlphaNum 32 | b64enc) }}
  jwt-secret: {{ $jwtSecret }}
  cross-service-key: {{ $crossServiceKey }}
