apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}
  labels:
    app: {{ .Values.riFirewall.hotfixYaraServer.name }}
    {{- with .Values.riFirewall.hotfixYaraServer.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "ri-firewall.annotations" . | nindent 4 }}
    {{- with .Values.riFirewall.hotfixYaraServer.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.riFirewall.hotfixYaraServer.name }}
  {{- if not .Values.riFirewall.hotfixYaraServer.hpa.enabled }}
  replicas: {{ .Values.riFirewall.authServer.deployment.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.riFirewall.hotfixYaraServer.name }}
        {{- with .Values.riFirewall.hotfixYaraServer.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "ri-firewall.annotations" . | nindent 8 }}
        {{- with .Values.riFirewall.hotfixYaraServer.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.riFirewall.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.riFirewall.hotfixYaraServer.name }}
          image: "{{ .Values.riFirewall.images.backendImage.registry}}/{{ .Values.riFirewall.images.backendImage.name }}"
          imagePullPolicy: {{ .Values.riFirewall.images.backendImage.pullPolicy }}
          ports:
            - name: yara
              containerPort: {{ .Values.riFirewall.hotfixYaraServer.port }}
              protocol: TCP
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:{{ .Values.riFirewall.hotfixYaraServer.port }}" ]
            periodSeconds: 5
            timeoutSeconds: 5
          startupProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:{{ .Values.riFirewall.hotfixYaraServer.port }}" ]
            failureThreshold: 60
            periodSeconds: 5
          env:
            - name: GH_INSTALLATION_ID
              value: "{{ .Values.riFirewall.hotfixYaraServer.installationID | default "53172568" }}" # Defaults to YARA-Auth-App installation ID
            - name: GH_APP_ID
              value: "{{ .Values.riFirewall.hotfixYaraServer.appID | default "954157" }}" # Defaults to YARA-Auth-App app ID
            - name: GH_PRIVATE_KEY_PEM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.riFirewall.secrets.existingIntegrationSecretsName }}
                  key: yaraGithubAppPem
            - name: RI_SERVICE_NAME
              value: {{ .Values.riFirewall.hotfixYaraServer.name }}
            {{- if .Values.riFirewall.registerFirewallAgent.enabled }}
            - name: AGENT_ID
              value: {{ .Values.riFirewall.registerFirewallAgent.agentID }}
            {{- end }}
          resources:
            {{- toYaml .Values.riFirewall.hotfixYaraServer.deployment.resources | nindent 12 }}
          command:
            - "/ri/firewall"
          args:
            - "start-yara-server"
            - "--server-config-path=/config/server.config"
            - "--port={{ .Values.riFirewall.hotfixYaraServer.port }}"
            - "--mount-dir=/yara"
            - "--auto-update-enabled={{ .Values.riFirewall.hotfixYaraServer.autoUpdateEnabled }}"
            - "--yara-patterns-git-ref={{ .Values.riFirewall.hotfixYaraServer.ruleRepoRef }}"
            {{ if ne .Values.riFirewall.hotfixYaraServer.yaraPatternUpdateFrequency "" }}
            - "--update-frequency={{ .Values.riFirewall.hotfixYaraServer.yaraPatternUpdateFrequency }}"
            {{ end }}
          volumeMounts:
            - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}-config
              mountPath: "/config"
              readOnly: true
            - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}-ephemeral-storage
              mountPath: "/yara"
      volumes:
        # Volumes are defined at the Pod level, then mounted into containers within that Pod
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}-config
          configMap:
            name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}-conf
            items:
              - key: "server.config"
                path: "server.config"
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.hotfixYaraServer.name }}-ephemeral-storage
          emptyDir: {}
