apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ri-firewall.generatedSecretsName" . }}
type: Opaque
data:
  # for auth-related secrets, always read from pre-existing secret to avoid interrupting in-flight workloads
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "ri-firewall.generatedSecretsName" .) ) | default dict }}
  {{- $secretData := (get $secret "data") | default dict }}
  apiKey: {{ (get $secretData "apiKey") | default (randAlphaNum 32 | b64enc) }}
  tokenSigningKey: {{ (get $secretData "tokenSigningKey") | default (randAlphaNum 32 | b64enc) }}
