{{- if (not .Values.riFirewall.secrets.existingAuthSecretsName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ri-firewall.existingSecretsName" . }}
type: Opaque
data:
  auth0ClientSecret: {{ .Values.riFirewall.secrets.auth0.clientSecret | b64enc | quote }}
  auth0ClientID: {{ .Values.riFirewall.secrets.auth0.clientID | b64enc | quote }}
  auth0Domain: {{ .Values.riFirewall.secrets.auth0.domain | b64enc | quote }}
  auth0CallbackURL: {{ .Values.riFirewall.secrets.auth0.callback | b64enc | quote }}
{{- end }}
