{{- if (not .Values.riFirewall.secrets.existingAuthSecretsName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ri-firewall.existingSecretsName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "ri-firewall.existingSecretsName" .) ) | default dict }}
  {{- $secretData := (get $secret "data") | default dict }}
  auth0ClientSecret: {{ (get $secretData "auth0ClientSecret") | default (.Values.riFirewall.secrets.auth0.clientSecret | b64enc | quote) }}
  auth0ClientID: {{ (get $secretData "auth0ClientID") | default (.Values.riFirewall.secrets.auth0.clientID | b64enc | quote) }}
  auth0Domain: {{ (get $secretData "auth0Domain") | default (.Values.riFirewall.secrets.auth0.domain | b64enc | quote) }}
  auth0CallbackURL: {{ (get $secretData "auth0CallbackURL") | default (.Values.riFirewall.secrets.auth0.callback | b64enc | quote) }}
  {{- if .Values.riFirewall.registerFirewallAgent.enabled }}
  # One-time use API key to register the firewall agent
  registerAgentAPIKey: {{ (get $secretData "registerAgentAPIKey") | default (.Values.riFirewall.registerFirewallAgent.apiKey | b64enc | quote) }}
  {{- end }}
{{- end }}
