{{- if .Values.rime.notificationsWorker.notificationsDigestCron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rime.fullname" . }}-{{ .Values.rime.notificationsWorker.notificationsDigestCron.name }}
  labels:
    app: {{ .Values.rime.notificationsWorker.notificationsDigestCron.name }}
      {{- include "rime.labels" . | nindent 4 }}
      {{- with .Values.rime.notificationsWorker.notificationsDigestCron.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  annotations:
      {{- include "rime.annotations" . | nindent 4 }}
      {{- with .Values.rime.notificationsWorker.notificationsDigestCron.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  schedule: "{{ .Values.rime.notificationsWorker.notificationsDigestCron.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.rime.notificationsWorker.notificationsDigestCron.name }}
            {{- include "rime.labels" . | nindent 12 }}
            {{- with .Values.rime.notificationsWorker.notificationsDigestCron.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            {{- include "rime.annotations" . | nindent 12 }}
            {{- with .Values.rime.notificationsWorker.notificationsDigestCron.annotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.rime.images.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: "digest-notif-worker"
              env:
                {{- include "rime.webAppHostEnv" . | nindent 16 }}
                {{- include "rime.commonEnv" . | nindent 16 }}
              image: "{{ .Values.rime.images.backendImage.registry}}/{{ .Values.rime.images.backendImage.name }}"
              imagePullPolicy: {{ .Values.rime.images.backendImage.pullPolicy }}
              command:
                - "/rime/digest_notif_worker"
                - "--server-config-path=/config/worker.config"
              volumeMounts:
                - name: {{ include "rime.fullname" . }}-worker-config
                  mountPath: "/config"
                  readOnly: true
                {{- if .Values.tls.enableCertManager }}
                - name: {{ include "rime.fullname" . }}-{{ .Values.rime.notificationsWorker.name }}-tls
                  mountPath: /var/tmp/tls/common
                  readOnly: true
                {{- end }}
                {{- include "rime.externalTLSSecretVolumeMounts" . | nindent 16 }}
          volumes:
            - name: {{ include "rime.fullname" . }}-worker-config
              {{- if ne .Values.rime.internalWorkerJobs.existingConfigSecretName "" }}
              secret:
                secretName: {{ .Values.rime.internalWorkerJobs.existingConfigSecretName }}
              {{- else }}
              configMap:
                name: {{ include "rime.fullname" . }}-worker-conf
              {{- end }}
                items:
                  - key: "worker.config"
                    path: "worker.config"
            {{- if .Values.tls.enableCertManager }}
            - name: {{ include "rime.fullname" . }}-{{ .Values.rime.notificationsWorker.name }}-tls
              secret:
                secretName: {{ include "rime.fullname" . }}-{{ .Values.rime.notificationsWorker.name }}-tls
            {{- end }}
            {{- include "rime.externalTLSSecretVolumes" . | nindent 12 }}
          restartPolicy: Never
      backoffLimit: 0
{{- end }}
