{{- if .Values.rime.initClusterMetadata.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rime.fullname" . }}-{{ .Values.rime.initClusterMetadata.name }}
  labels:
    {{- include "rime.labels" . | nindent 4 }}
    {{- with .Values.rime.initClusterMetadata.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    # NOTE: post-upgrade relies on the database-setup script being idempotent.
    "helm.sh/hook": post-install,post-upgrade
    # Hooks are sorted in ascending order -> this should run after the index creation job.
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- include "rime.annotations" . | nindent 4 }}
    {{- with .Values.rime.initClusterMetadata.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "rime.labels" . | nindent 8 }}
        {{- with .Values.rime.initClusterMetadata.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "rime.annotations" . | nindent 8 }}
        {{- with .Values.rime.initClusterMetadata.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "rime.monitoringAnnotations" (dict "monitoring" .Values.rime.monitoring "name" .Values.rime.initClusterMetadata.name ) | nindent 8 }}
    spec:
      {{- with .Values.rime.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rime.featureFlagServer.fetchLicenseFromS3 }}
      serviceAccountName:  {{ include "rime.featureFlagServer.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.rime.initClusterMetadata.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.rime.initClusterMetadata.name }}
          env:
            {{- include "rime.commonEnv" . | nindent 12 }}
            {{- include "rime.featureFlagEnv" . | nindent 12 }}
            {{- include "rime.webAppHostEnv" . | nindent 12 }}
            - name: SMTP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: smtpEmail
                  optional: true
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: smtpPassword
                  optional: true
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: smtpServer
                  optional: true
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: smtpPort
                  optional: true
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: adminUsername
                  optional: true
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: adminPassword
                  optional: true
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: oidcClientID
                  optional: true
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: oidcClientSecret
                  optional: true
            - name: OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: oidcIssuerURL
                  optional: true
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rime.commonSecretName" . }}
                  key: openaiApiKey
                  optional: true
          image: "{{ .Values.rime.images.backendImage.registry}}/{{ .Values.rime.images.backendImage.name }}"
          imagePullPolicy: "{{ .Values.rime.images.backendImage.pullPolicy }}"
          command:
            - "/rime/dbworker"
          args:
            - "init-cluster-metadata"
            - "--server-config-path=/config/worker.config"
            - "-overwrite-feature-flags={{ .Values.rime.initClusterMetadata.overwriteLicense }}"
            {{if .Values.rime.imageRegistryServer.enabled }}
            - "--initialize-image-registry"
            {{end }}
            # 4 minute timeout because the maximum execution time for a helm chart hook is 5 min.
            - "-timeout=4m"
            {{- if .Values.rime.verbose }}
            - "-verbose"
            {{- end }}
            {{- if .Values.rime.initClusterMetadata.debug }}
            - "-debug"
            {{- end}}
          volumeMounts:
            - name: {{ include "rime.fullname" . }}-worker-config
              mountPath: "/config"
              readOnly: true
            {{- if .Values.tls.enableCertManager }}
            - name: {{ include "rime.fullname" . }}-{{ .Values.rime.initClusterMetadata.name }}-tls
              mountPath: /var/tmp/tls/common
              readOnly: true
            {{- end }}
            {{- include "rime.externalTLSSecretVolumeMounts" . | nindent 12 }}
      restartPolicy: OnFailure
      volumes:
        - name: {{ include "rime.fullname" . }}-worker-config
        {{- if ne .Values.rime.internalWorkerJobs.existingConfigSecretName "" }}
          secret:
            secretName: {{ .Values.rime.internalWorkerJobs.existingConfigSecretName }}
        {{- else }}
          configMap:
            name: {{ include "rime.fullname" . }}-worker-conf
        {{- end }}
            items:
              - key: "worker.config"
                path: "worker.config"
        {{- if .Values.tls.enableCertManager }}
        - name: {{ include "rime.fullname" . }}-{{ .Values.rime.initClusterMetadata.name }}-tls
          secret:
            secretName: {{ include "rime.fullname" . }}-{{ .Values.rime.initClusterMetadata.name }}-tls
        {{- end }}
        {{- include "rime.externalTLSSecretVolumes" . | nindent 8 }}
  backoffLimit: {{ .Values.rime.initClusterMetadata.backoffLimit }}
{{- end }}
