apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rime.fullname" . }}-{{ .Values.rime.storageManagerServer.name }}
  labels:
    app: {{ .Values.rime.storageManagerServer.name }}
    {{- include "rime.labels" . | nindent 4 }}
    {{- with .Values.rime.storageManagerServer.sts.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "rime.annotations" . | nindent 4 }}
    {{- with .Values.rime.storageManagerServer.sts.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.rime.storageManagerServer.name }}
      {{- include "rime.selectorLabels" . | nindent 6 }}
  {{- if not .Values.rime.storageManagerServer.hpa.enabled }}
  replicas: {{ .Values.rime.storageManagerServer.sts.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.rime.storageManagerServer.name }}
        {{- include "rime.labels" . | nindent 8 }}
        {{- with .Values.rime.storageManagerServer.sts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "rime.annotations" . | nindent 8 }}
        {{- with .Values.rime.storageManagerServer.sts.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "rime.monitoringAnnotations" (dict "monitoring" .Values.rime.monitoring "name" .Values.rime.storageManagerServer.name ) | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/web-server/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.rime.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rime.storageManagerServer.sts.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rime.storageManagerServer.serviceAccountName" . }}
      containers:
        - name: {{ .Values.rime.storageManagerServer.name }}
          env:
            {{- include "rime.webAppHostEnv" . | nindent 12 }}
            {{- include "rime.commonEnv" . | nindent 12 }}
            {{- with .Values.rime.storageManagerServer.sts.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: RI_SERVICE_NAME
              value: {{ .Values.rime.storageManagerServer.name }}
          image: "{{ .Values.rime.images.backendImage.registry}}/{{ .Values.rime.images.backendImage.name }}"
          imagePullPolicy: {{ .Values.rime.images.backendImage.pullPolicy }}
          ports:
            - name: sms
              containerPort: {{ .Values.rime.storageManagerServer.port }}
              protocol: TCP
            - name: sms-grpc
              containerPort: {{ .Values.rime.storageManagerServer.grpcPort }}
              protocol: TCP
            - name: sms-debug
              containerPort: 6060
              protocol: TCP
          resources:
            {{- toYaml .Values.rime.storageManagerServer.sts.resources | nindent 12 }}
          command: [ "/bin/sh","-c" ]
          args: [ "( while : ; do date; sleep 60; done )" ]
          volumeMounts:
            {{- if .Values.tls.enableCertManager }}
            - name: {{ include "rime.fullname" . }}-{{ .Values.rime.storageManagerServer.name }}-tls
              mountPath: /var/tmp/tls/common
              readOnly: true
            {{- end }}
            {{- include "rime.externalTLSSecretVolumeMounts" . | nindent 12 }}
            {{- with .Values.rime.storageManagerServer.sts.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        # Volumes are defined at the Pod level, then mounted into containers within that Pod
        {{- if .Values.tls.enableCertManager }}
        - name: {{ include "rime.fullname" . }}-{{ .Values.rime.storageManagerServer.name }}-tls
          secret:
            secretName: {{ include "rime.fullname" . }}-{{ .Values.rime.storageManagerServer.name }}-tls
        {{- end }}
        {{- include "rime.externalTLSSecretVolumes" . | nindent 8 }}
        {{- with .Values.rime.storageManagerServer.sts.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.rime.storageManagerServer.sts.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rime.storageManagerServer.sts.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rime.storageManagerServer.sts.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
