apiVersion: v1
kind: Secret
metadata:
  name: rime-jwt-secret
type: Opaque
data:
  # retrieve secret if it already exists
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace "rime-jwt-secret") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 32) }}
  jwt-secret: {{ $jwtSecret | b64enc | quote }}
