{{- if .Values.hybridDeploymentApiKeySecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hybridDeploymentApiKeySecret.name }}
type: Opaque
data:
  # This is just a placeholder value. You should update this secret using kubectl after deployment.
  api-key: {{ "YXBpLWtleQ==" | quote }} # "api-key" in base64
{{- end }}
