{{- if .Values.hybridDeploymentApiKeySecret.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.hybridDeploymentApiKeySecret.name }}-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  resourceNames: ["{{ .Values.hybridDeploymentApiKeySecret.name }}"]
{{- end }}
