{{- if .Values.onpremGateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ai-defense-onpremises.labels" . | nindent 4 -}}
    {{- toYaml .Values.onpremGateway.labels| nindent 4 }}
  name: {{  .Values.onpremGateway.serviceAccount.name }}
{{ end }}
