apiVersion: v1
kind: ConfigMap
metadata:
  name: onprem-gw-service-config
  labels:
    {{- include "ai-defense-onpremises.labels" . | nindent 4 -}}
    {{- toYaml .Values.onpremGateway.labels | nindent 4 }}
data:
  onprem-gw-service-config.yaml: |
    service_endpoints_map:
      {{- range $key, $value := .Values.onpremGateway.serviceEndpoints }}
      {{ $key | upper }}: {{ $value | quote }}
      {{- end }}
