apiVersion: v1
kind: Secret
metadata:
  name: validation-abx-secrets-terraform
type: Opaque
data:
  huggingfaceAPIKey: {{ .Values.huggingfaceAPIKey }}
  yaraGithubAppPem: {{ .Values.yaraGithubAppPem }}
