{{- if .Values.rimeAgent.agentDeploymentLauncher.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rime-agent.fullname" . }}-{{ .Values.rimeAgent.agentDeploymentLauncher.name }}-conf
data:
  server.config: |
{{ include "rime-agent.serverArgs" . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rime-upgrade-agent-id
data:
  agentID: ""
{{- end }}
