apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}
  labels:
    app: {{ .Values.riFirewall.yaraServer.name }}
    {{- with .Values.riFirewall.yaraServer.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "ri-firewall.annotations" . | nindent 4 }}
    {{- with .Values.riFirewall.yaraServer.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.riFirewall.yaraServer.name }}
  {{- if not .Values.riFirewall.yaraServer.hpa.enabled }}
  replicas: {{ .Values.riFirewall.authServer.deployment.replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.riFirewall.yaraServer.name }}
        {{- with .Values.riFirewall.yaraServer.deployment.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "ri-firewall.annotations" . | nindent 8 }}
        {{- with .Values.riFirewall.yaraServer.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.riFirewall.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.riFirewall.yaraServer.name }}
          image: "{{ .Values.riFirewall.images.backendImage.registry}}/{{ .Values.riFirewall.images.backendImage.name }}"
          imagePullPolicy: {{ .Values.riFirewall.images.backendImage.pullPolicy }}
          ports:
            - name: yara
              containerPort: {{ .Values.riFirewall.yaraServer.port }}
              protocol: TCP
          env:
            - name: YARA_RULES_AUTOUPDATE_ENABLED
              value: "{{ .Values.riFirewall.yaraServer.autoUpdateEnabled }}"
            - name: YARA_RULE_REPO_REF
              value: {{ .Values.riFirewall.yaraServer.ruleRepoRef }}
          resources:
            {{- toYaml .Values.riFirewall.yaraServer.deployment.resources | nindent 12 }}
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do cat /config/server.config && sleep 30; done;" ]
          volumeMounts:
            - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}-config
              mountPath: "/config"
              readOnly: true
            - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}-ephemeral-storage
              mountPath: "/yara"
      volumes:
        # Volumes are defined at the Pod level, then mounted into containers within that Pod
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}-config
          configMap:
            name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}-conf
            items:
              - key: "server.config"
                path: "server.config"
        - name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraServer.name }}-ephemeral-storage
          emptyDir: {}
