{{- if not .Values.rimeAgent.isInternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime-agent.generatedSecretsName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  # for auth-related secrets, always read from pre-existing secret to avoid interrupting in-flight workloads
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "rime-agent.generatedSecretsName" .) ) | default dict }}
  {{- $secretData := (get $secret "data") | default dict }}
  crossServiceKey: {{ (get $secretData "crossServiceKey") | default (randAlphaNum 32 | b64enc) }}
{{- end }}
