{{- if (and (eq (len .Values.rimeAgent.images.imagePullSecrets) 0) .Values.rimeAgent.dockerCredentialsPayload)   -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime-agent.dockerSecretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.rimeAgent.dockerCredentialsPayload | quote}}
{{- end }}
