apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime-agent.secretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  api-key: {{ default "" .Values.rimeAgent.apiKey | b64enc | quote}}
