{{- if (and (eq (len .Values.rimeAgent.images.imagePullSecrets) 0) .Values.rimeAgent.dockerCredentialsPayload)   -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime-agent.dockerSecretName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.rimeAgent.dockerCredentialsPayload | quote}}
{{- end }}
