{{- if (eq (len .Values.rimeAgent.imagePullSecrets) 0) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rime-agent.dockerSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.rimeAgent.dockerCredentialsPayload}}
  .dockerconfigjson: {{ .Values.rimeAgent.dockerCredentialsPayload | quote}}
  {{- else }}
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.rimeAgent.dockerCredentials.registry (printf "%s:%s" .Values.rimeAgent.dockerCredentials.username .Values.rimeAgent.dockerCredentials.password | b64enc) | b64enc }}
  {{- end }}
{{- end }}
