{{- if .Values.riFirewall.licenseServer.serviceAccount.create }}
# Binds License server service account to a role providing read access to
# k8s resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ri-firewall.licenseServer.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ri-firewall.licenseServer.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ri-firewall.licenseServer.serviceAccountName" . }}
{{- end }}
