{{- if .Values.riFirewall.yaraOperator.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ri-firewall.fullname" . }}-{{ .Values.riFirewall.yaraOperator.name }}
spec:
  minAvailable: {{ .Values.riFirewall.yaraOperator.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.riFirewall.yaraOperator.name }}
{{ end }}
