apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rime.fullname" . }}-{{ .Values.rime.modelTestingServer.name }}-conf
data:
  server.config: |
{{ include "rime.serverArgs" . | indent 4 }}
    modelTests:
      managedImages:
        allow_external_custom_images: true
      spark:
        allowSparkJobs: {{ contains "rime-testing-engine-spark" .Values.rime.images.modelTestingImage.name }}
      crossServiceKeyRef:
        secretName: {{ include "rime.generatedSecretsName" . }}
        key: crossServiceKey
