{{- if .Values.rime.modelTestingServer.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rime.modelTestingServer.serviceAccountName" . }}
  labels:
    {{- include "rime.labels" . | nindent 4 }}
  annotations:
    {{- include "rime.annotations" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [list]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
  - apiGroups: ["", "batch"]
    resources: [jobs]
    verbs: [get, list]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create, get, update]
{{- end }}
