riFirewall:
  commonAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    ad.datadoghq.com/tags: '{"user":"firewall-abx"}'

  secrets:
    existingIntegrationSecretsName: firewall-abx-secrets-terraform
    auth0Enabled: false

  productionOptimizations:
    overprovisionGPUNode:
      enabled: true
    overprovisionComputeNode:
      enabled: true

  images:
    backendImage:
      name: "robustintelligencehq/firewall-backend:2.12.0-rc.9"
      pullPolicy: "IfNotPresent"
    firewallServerImage:
      name: "robustintelligencehq/ri-firewall:2.12.0-rc.9"
      pullPolicy: "IfNotPresent"
    modelServerImage:
      name: "robustintelligencehq/firewall-model-server:2.12.0-rc.9"
      pullPolicy: "IfNotPresent"

  rimeFirewallDeployment:
    enabled: false

  operator:
    firewallInstanceIngress:
      disabled: true
    firewallInstanceTemplate:
      hpa:
        minReplicas: 2
        maxReplicas: 10

  firewallSystemConfig:
    enableHotfixYara: true
    validateResponseVisibilitySettings:
      ruleEvalMetadataVisibility:
        enableStdoutLogging: true
        enableApiResponse: true
      firewallRequestVisibility:
        enableStdoutLogging: true
        enableApiResponse: true
  hotfixYaraServer:
    autoUpdateEnabled: false
    ruleRepoRef: "main"
    yaraPatternUpdateFrequency: ""
    hpa:
      minReplicas: 2
      maxReplicas: 10
    deployment:
      replicaCount: 2
  shimServer:
    name: "shim"
    enabled: true
    hpa:
      minReplicas: 2
      maxReplicas: 10
    deployment:
      replicaCount: 2

  tracing:
    # -- Whether to enable OpenTelemetry tracing for all services on the Firewall
    enabled: true
    env_name: "prod"
    otel_remote_backend_grpc_port: "4317"
    cluster_name: "prod-ai-defense-us-east-1"
    namespace: "prod-runtime"

  registerFirewallAgent:
    enabled: true
    name: "register-firewall-agent-job"
    agentID: "ac1be15a-7f5b-4332-a5d0-495fede529c7"
    platformAddress: "https://rime.abx.rbst.io"
    agentURL: "firewall.abx.rbst.io"
    apiKey: "d9e46f658a7c068bb53daafe9ed6d642"
    backoffLimit: 2
    serviceAccount:
      create: true
      name: ""
      annotations: {}
      labels: {}
    job:
      labels: {}
      annotations: {}
      securityContext: {}
      resources:
        limits:
          memory: "100Mi"
        requests:
          memory: "100Mi"
          cpu: "100m"

  modelServers:
    promptInjectionMulticlass:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    promptInjectionBinary:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    toxicityIntentMultiLabel:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    toxicityIntentModel:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    toxicity:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    toxicityInterpretability:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    toxicityJa:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    xlmMultilingualToxicity:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
    xlmMultilingualHarmful:
      resources:
        limits:
          gpu: 2
        max_replicas: 10
        min_replicas: 1
        requests:
          gpu: 2
