# Default values for ri-detection-resources.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common annotations added to all K8s resources
commonAnnotations: {}
# Common labels added to all K8s resources
commonLabels: {}

# -- Image specification for the RI detection resources.
# @default -- (see individual values in `values.yaml`)
images:
  imagePullSecrets:
    - name: rimecreds
  modelServerImage:
    registry: "docker.io"
    name: "robustintelligencehq/firewall-model-server:latest"
    pullPolicy: "Always"

# -- Values for the internal RI K8 secret used by the detection resources.
# @default -- (see individual values in `values`.yaml)
secrets:
  # If existingIntegrationSecretsName is set, the secret will not be created.
  # Must have huggingfaceAPIKey key set.
  existingIntegrationSecretsName: ""

# -- `modelServers` K8s-level configurations
# @default -- (see individual values in `values.yaml`)
modelServers:
  # The following section of model server config values between the comments
  # is autogenerated by the autogen script. The start and end delimiter
  # comments should not be changed and are used to identify the section that
  # should be autogenerated.
  ## START MODEL SERVER VALUES
    promptInjection:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    promptInjectionPrivacy:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    toxicity:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    llmRejection:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    factualInconsistency:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "2600Mi"
          cpu: "1000m"
        limits:
          memory: "2600Mi"
          cpu: "5000m"
    languageDetection:
      enabled: true
      maxReplicas: 1
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "600Mi"
          cpu: "1000m"
        limits:
          memory: "600Mi"
          cpu: "5000m"
    textEmbedding:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "900Mi"
          cpu: "1000m"
        limits:
          memory: "900Mi"
          cpu: "5000m"
    toxicityInterpretability:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    ## END MODEL SERVER VALUES
