commonAnnotations:
  ad.datadoghq.com/tags: '{"user":"firewall-abx"}'
  prometheus.io/scrape: 'true'
  prometheus.io/port: '8080'

secrets:
  existingIntegrationSecretsName: firewall-abx-secrets-terraform

images:
  modelServerImage:
    name: "robustintelligencehq/firewall-model-server:2.11.0-rc.11"
    pullPolicy: "IfNotPresent"
  firewallBackendImage:
    name: "robustintelligencehq/firewall-backend:2.11.0-rc.11"
    pullPolicy: "IfNotPresent"

modelServers:
  promptInjectionMulticlass:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  promptInjectionBinary:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  toxicity:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  refusalHarmfulDetector:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  factualInconsistency:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  toxicityInterpretability:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  factualInconsistencyJa:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
  toxicityJa:
    resources:
      requests:
        gpu: 1
      limits:
        gpu: 1
