# Default values for ri-detection-resources.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common annotations added to all K8s resources
commonAnnotations: {}
# Common labels added to all K8s resources
commonLabels: {}

# -- Image specification for the RI detection resources.
# @default -- (see individual values in `values.yaml`)
images:
  imagePullSecrets:
    - name: rimecreds
  modelServerImage:
    registry: "docker.io"
    name: "robustintelligencehq/firewall-model-server:latest"
    pullPolicy: "Always"
  firewallBackendImage:
    registry: "docker.io"
    name: "robustintelligencehq/firewall-backend:latest"
    pullPolicy: "Always"

# -- Values for the internal RI K8 secret used by the detection resources.
# @default -- (see individual values in `values`.yaml)
secrets:
  # If existingIntegrationSecretsName is set, the secret will not be created.
  # Must have huggingfaceAPIKey key set.
  existingIntegrationSecretsName: ""

# -- `modelServers` K8s-level configurations
# @default -- (see individual values in `values.yaml`)
modelServers:
  # The following section of model server config values between the comments
  # is autogenerated by the autogen script. The start and end delimiter
  # comments should not be changed and are used to identify the section that
  # should be autogenerated.
  ## START MODEL SERVER VALUES
    promptInjectionMulticlass:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-prompt-injection-multiclass:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    toxicity:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-toxicity:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    llmRejection:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-llm-rejection:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1100Mi"
          cpu: "1000m"
        limits:
          memory: "1100Mi"
          cpu: "5000m"
    factualInconsistency:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-factual-inconsistency:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "2600Mi"
          cpu: "1000m"
        limits:
          memory: "2600Mi"
          cpu: "5000m"
    languageDetection:
      enabled: true
      maxReplicas: 1
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-language-detection:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1000Mi"
          cpu: "1000m"
        limits:
          memory: "1000Mi"
          cpu: "5000m"
    textEmbedding:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-text-embedding:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1300Mi"
          cpu: "1000m"
        limits:
          memory: "1300Mi"
          cpu: "5000m"
    toxicityInterpretability:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-toxicity-interpretability:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1700Mi"
          cpu: "1000m"
        limits:
          memory: "1700Mi"
          cpu: "5000m"
    factualInconsistencyJa:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-factual-inconsistency-ja:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "3300Mi"
          cpu: "1000m"
        limits:
          memory: "3300Mi"
          cpu: "5000m"
    textEmbeddingJa:
      enabled: true
      maxReplicas: 3
      minReplicas: 1
      # Settings for loading the model from an artifact cached in the Docker image
      # instead of downloading it during server startup time.
      useCachedArtifact:
        enabled: false
        dockerImageOverride:
          registry: "docker.io"
          name: "robustintelligencehq/firewall-model-server-text-embedding-ja:latest"
          pullPolicy: "Always"
      # Use an existing model server outside the cluster instead of spinning up a
      # model server in this Helm deployment.
      # Only enable this for local Minikube.
      remoteModelServer:
        enabled: false
        address: ""
      resources:
        requests:
          memory: "1300Mi"
          cpu: "1000m"
        limits:
          memory: "1300Mi"
          cpu: "5000m"
    ## END MODEL SERVER VALUES

signalgenYaraServer:
  name: "signalgen-yara"
  port: 5025
  service:
    type: ClusterIP
    annotations:
    labels:
  hpa:
    annotations:
    labels:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
  deployment:
    annotations:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    labels:
    replicaCount: 1
    resources:
      limits:
        memory: 150Mi
      requests:
        cpu: 200m
        memory: 150Mi
