{{- if .Values.rime.uploadServer.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rime.uploadServer.serviceAccountName" . }}
  labels:
    {{- include "rime.labels" . | nindent 4 }}
  annotations:
    {{- include "rime.annotations" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: ["*"]
{{- end }}
